CREATE TABLE payments (
    id UUID PRIMARY KEY,
    transaction_id VARCHAR(100) NOT NULL,
    order_id VARCHAR(100),
    amount NUMERIC(14,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    status VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    payment_method VARCHAR(50),
    transaction_hash VARCHAR(128) UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE settlements (
    id UUID PRIMARY KEY,
    settlement_id VARCHAR(100) NOT NULL,
    reference VARCHAR(100) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL
);

CREATE TABLE ledger_entries (
    id UUID PRIMARY KEY,
    ledger_id VARCHAR(100) NOT NULL,
    reference VARCHAR(100) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    entry_type VARCHAR(50) NOT NULL
);

CREATE TABLE reconciliation_results (
    id UUID PRIMARY KEY,
    reconciliation_id UUID NOT NULL,
    payment_id UUID,
    settlement_id UUID,
    ledger_id UUID,
    status VARCHAR(50) NOT NULL,
    expected_amount NUMERIC(14,2),
    actual_amount NUMERIC(14,2),
    difference NUMERIC(14,2),
    confidence DOUBLE PRECISION NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exceptions (
    id UUID PRIMARY KEY,
    reconciliation_id UUID NOT NULL,
    transaction_id VARCHAR(100),
    type VARCHAR(50) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    id UUID PRIMARY KEY,
    reconciliation_id UUID NOT NULL,
    transaction_id VARCHAR(100),
    action VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reconciliation_requests (
    id UUID PRIMARY KEY,
    request_hash VARCHAR(128) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reconciliation_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(255),
    matched_id VARCHAR(255),
    status VARCHAR(50),
    reason VARCHAR(500),
    confidence DOUBLE PRECISION NOT NULL,
    tier VARCHAR(100),
    created_at TIMESTAMP
);
